### PR TITLE
Updated the service worker to install an extended cache of resources.…

### PR DESCRIPTION
**Pull request by notrodes**
… And removed verbose code in app.js that just made scope more explicit. In all files I changed callbacks to use arrow functions, const declarations and strict equality checks.

### CODE REVIEW

**Comment by notrodes** [comment]
I have checked this, for testing chrome is a great debug tool. Firefox does not show service worker info in its debug tools but chrome does.

**Comment by notrodes** [comment]
hellooo

**Review by Ruborcalor — APPROVED** [review]
Great stuff thanks for taking care of this :thumbsup:

**Comment by psvenk** [comment]
> Great stuff thanks for taking care of this +1

@Ruborcalor Ready to merge?

**Comment by Ruborcalor** [comment]
Yes looks good to merge

**Pull request merged**
