### PR TITLE
Client-side JSON import/export

### PR DESCRIPTION
**Pull request by psvenk**
Implements #74 at long last. Please see that issue and the commit messages for more details.

### CODE REVIEW

**Comment by psvenk** [comment]
Some things to do before merging (from my conversation with @kdk1616):
- [x] On the login page, say "Use Aspen credentials or leave blank **to import data**"
- [x] Add a mouseover to each disabled term in the export dialog stating the reason why the term is disabled (term is not available on Aspen, or term is not included in the imported data)
- [x] Grey out inaccessible quarters in the quarter dropdown

**Comment by psvenk** [comment]
I just now found a bug: if more than one object is in tableData (e.g.
scraped data and imported data), then the quarter dropdown does not
adjust on switching currentTableData. A fix is underway.

**Comment by psvenk** [comment]
Also, further testing is needed regarding how switching `currentTableData` affects calculated grades (see `termsReset`) and different formats of GPA.

**Comment by Ruborcalor** [comment]
Great stuff! Some ideas.

1. When logging in and then importing data, the term selector doesn't fully reset.  In the screenshot below I imported only two terms, but all four still appear available in the term selector. What do you think about indicating which ones were included in the import?
<details>
 <summary>Term Selector</summary>

</details>

2. The default behavior seems to be that when navigating to home.html, you are prompted for an import file, however I imagine that most users would prefer to be redirected back to the login.html page if their session timed out.

**Comment by psvenk** [comment]
@Ruborcalor Thanks for the review.

On 4/21/20 6:09 PM, Cole Killian wrote:

> Great stuff! Some ideas.
> 
>  1. When logging in and then importing data, the term selector doesn't
>     fully reset. In the screenshot below I imported only two terms, but
>     all four still appear available in the term selector. What do you
>     think about indicating which ones were included in the import?

I think this is caused by two of the issues that I mentioned above:

> - Grey out inaccessible quarters in the quarter dropdown
>
> - If more than one object is in tableData (e.g. scraped data and
>   imported data), then the quarter dropdown does not adjust on switching
>   currentTableData.

Sorry, I may not have worded them very well. Hopefully the issue that
you noticed will be resolved when my fix is done.

>  2. The default behavior seems to be that when navigating to home.html,
>     you are prompted for an import file, however I imagine that most
>     users would prefer to be redirected back to the login.html page if
>     their session timed out.

I imagined that most users would navigate to the / endpoint (which now
redirects since faed11dedf to the correct page depending on whether or
not there is an active session) without accounting for the fact that
people may have bookmarked /home.html.

This can probably be fixed by redirecting home.html to login.html
server-side when there is no active session, and creating a dummy
session when a user clicks on "Login" leaving the username and password
fields blank.

**Comment by psvenk** [comment]
> - On the login page, say "Use Aspen credentials or leave blank **to import data**"
> - Add a mouseover to each disabled term in the export dialog stating the reason why the term is disabled (term is not available on Aspen, or term is not included in the imported data)

Fixed in 7ec1869a3f.

> - Grey out inaccessible quarters in the quarter dropdown

Fixed in 89a9c67106.

> - If more than one object is in tableData (e.g. scraped data and imported data), then the quarter dropdown does not adjust on switching currentTableData.

Fixed in 4e87e1e114.

Remaining things to do:

- > The default behavior seems to be that when navigating to home.html, you are prompted for an import file, however I imagine that most users would prefer to be redirected back to the login.html page if their session timed out.
- Instead of using the HTML `title` element for tooltips, use CSS and/or JavaScript to make a more accessible alternative that works on mobile devices and works with assistive technologies. See [MDN][1] and [Inclusive Components][2] for more info.
  + This is a good opportunity to mention that the accessibility of Aspine is not optimal and that we should add semantic attributes (among other improvements) at some point.
- Fix `build-lite.sh` to work properly after 05435d62b8.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
[2]: https://inclusive-components.design/tooltips-toggletips/

**Comment by psvenk** [comment]
Approval has been secured from @notrodes

**Review by notrodes — APPROVED** [review]
Yeah good work dudeman.

**Comment by psvenk** [comment]
Another thing to fix: The version detection for imports currently only checks the major version. We need to warn the user if the minor version of the import is newer than the minor version of Aspine, letting them know that they should use a newer version of Aspine to view the file (presumably Aspine lite).

**Comment by psvenk** [comment]
I would like to note that the solution employed in 89a9c67106 is hacky in that it uses `setTimeout` to defer loading the term dropdown, and we should aim for a more sustainable solution in the future.

**Comment by psvenk** [comment]
Note to self re hackiness of solution: this can be fixed by rewriting `isAccessible` to take an optional argument which specifies which terms are included in an import (in the case of imported data) and reads that argument if it is present.

We can probably get away with not passing in anything like that for scraped data as long as `currentTableData.overview` is populated. IIRC that is the only field that is checked for scraped data.

**Comment by psvenk** [comment]
> I would like to note that the solution employed in [89a9c67](https://github.com/Aspine/aspine/commit/89a9c6710640b356518395f3a025ca10239aac31) is hacky in that it uses `setTimeout` to defer loading the term dropdown, and we should aim for a more sustainable solution in the future.

Fixed in d939809c43.

**Comment by psvenk** [comment]
> The default behavior seems to be that when navigating to home.html, you are prompted for an import file, however I imagine that most users would prefer to be redirected back to the login.html page if their session timed out.

Fixed in 3393b11583.

**Comment by psvenk** [comment]
> Fix `build-lite.sh` to work properly after [05435d6](https://github.com/Aspine/aspine/commit/05435d62b8b07c67889f7398b0f118764f02d9b5).

Fixed in d61f403a24.

Remaining issues:

> Instead of using the HTML `title` element for tooltips, use CSS and/or JavaScript to make a more accessible alternative that works on mobile devices and works with assistive technologies. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) and [Inclusive Components](https://inclusive-components.design/tooltips-toggletips/) for more info.

> The version detection for imports currently only checks the major version. We need to warn the user if the minor version of the import is newer than the minor version of Aspine, letting them know that they should use a newer version of Aspine to view the file (presumably Aspine lite).

**Comment by psvenk** [comment]
> Instead of using the HTML `title` element for tooltips, use CSS and/or JavaScript to make a more accessible alternative that works on mobile devices and works with assistive technologies. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) and [Inclusive Components](https://inclusive-components.design/tooltips-toggletips/) for more info.

Fixed in db0604dfa6.

**Comment by psvenk** [comment]
> > Instead of using the HTML `title` element for tooltips, use CSS and/or JavaScript to make a more accessible alternative that works on mobile devices and works with assistive technologies. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) and [Inclusive Components](https://inclusive-components.design/tooltips-toggletips/) for more info.
> 
> Fixed in [db0604d](https://github.com/Aspine/aspine/commit/db0604dfa667c36dc7cfebf04f368bffd522ddcd).

Sorry, wrong issue

**Comment by psvenk** [comment]
> The version detection for imports currently only checks the major version. We need to warn the user if the minor version of the import is newer than the minor version of Aspine, letting them know that they should use a newer version of Aspine to view the file (presumably Aspine lite).

Fixed in db0604dfa6.

**Comment by psvenk** [comment]
> Instead of using the HTML `title` element for tooltips, use CSS and/or JavaScript to make a more accessible alternative that works on mobile devices and works with assistive technologies. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) and [Inclusive Components](https://inclusive-components.design/tooltips-toggletips/) for more info.

Fixed in 847ba33471.

All of the blockers that have been identified so far have been fixed.

@Ruborcalor @kdk1616 @notrodes Please take a look. Is this ready to merge?

**Review by Ruborcalor — APPROVED** [review]
Looks good to merge

**Review by kdk1616 — APPROVED** [review]

**Pull request merged**
