### PR TITLE
Refactored package.json (old)

### PR DESCRIPTION
**Pull request by notrodes**
in accordance with npm docs ([here](https://docs.npmjs.com/configuring-npm/package-json.html#people-fields-author-contributors)). Moved lines, changed from author field to contributors field. Updated repository.

### CODE REVIEW

**Comment by notrodes** [comment]
now server can be started with `npm start`

**Comment by notrodes** [comment]
Dont test this now its not working

**Comment by psvenk** [comment]
These changes look good; I'll test them later tonight. However, I see that you have changed double quotes to single quotes in some places. Is there a concrete reason for this? From what I have seen, most of the Aspine code uses double quotes for strings. My rationale for generally using double quotes (unless there are nested quotes) is that it is works across languages.

**Comment by notrodes** [comment]
@psvenk no real reason I just decided to use single quotes from now on because it is less keystrokes and wanted stuff to match.

**Comment by psvenk** [comment]
@notrodes ~~I'll amend your commit and remove the quote changes for the time being to be consistent with the rest of the code base, then.~~ *I see that the overall convention in backend code is single quotes, so I'll leave your commits as-is.* When we freeze the repo as per #96, maybe we can consider ~~changing the convention if there is a strong reason to do so~~ *imposing a uniform convention*.

**Comment by notrodes** [comment]
I deleted the repository this came from.

**Comment by psvenk** [comment]
Superseded by #106 because @notrodes deleted the repository from which this pull request was initiated.

**Pull request closed without merging**
