### PR TITLE
Use NODE_ENV to detect production/development

### PR DESCRIPTION
**Pull request by psvenk**
Following the changes to the CLI in pull request #233, bring back the `start.sh` script to minimize confusion.

### CODE REVIEW

**Comment by notrodes** [comment]
just make a npm run debug script, dont add a file

**Comment by psvenk** [comment]
> just make a npm run debug script, dont add a file

@notrodes What are your thoughts on making use of the `NODE_ENV` environment variable to detect whether to use HTTP or HTTPS by default, with `-s,--secure` and `-i,--insecure` available as overrides? That way, we could use the same `npm start` script (and `restart-serve.sh` would need to be updated to set `NODE_ENV=production`).

**Comment by notrodes** [comment]
> > just make a npm run debug script, dont add a file
> 
> @notrodes What are your thoughts on making use of the `NODE_ENV` environment variable to detect whether to use HTTP or HTTPS by default, with `-s,--secure` and `-i,--insecure` available as overrides? That way, we could use the same `npm start` script (and `restart-serve.sh` would need to be updated to set `NODE_ENV=production`).

Good idea

**Review by tektaxi — APPROVED** [review]
Looks good. Glad to have an easy start method again.

**Pull request merged**
