### PR TITLE
Fix period numbering under clock

### LINKED ISSUE #199: Period numbering incorrect in clock
When a student has a different number of classes on black days than on silver days (particularly when there is an AM block in one but not the other), the period names do not update when switching between black and silver.

### PR DESCRIPTION
**Pull request by jadebuckwalter**
Write a conditional to check whether a schedule includes a "before
school" class, as well as to align the black and silver day schedules.

### CODE REVIEW

**Review by psvenk — CHANGES_REQUESTED** [review]
This seems to work with my schedule, but it seems a bit hacky. Instead of computing an index using the period number (`Number(default_name.charAt(default_name.length - 1))`), we could just compare the last character of `default_name` with the last character of each entry of `period_names[bs_day]` (`for (const { name } of period_names[bs_day]) { ... }`, for example). If there is a match, then we can assume that this is the correct period and return the name; if no match, then just return the `default_name`. This way, we don't have to special-case "Before School" (AM) classes, we don't need to assume that they all have the words "Before School" in the title, we don't have separate logic for black and silver days, and the code is overall a lot simpler. Your thoughts?

**Comment by jadebuckwalter** [comment]
@psvenk Yes, that's a better idea.

**Comment by jadebuckwalter** [comment]
@psvenk This should work, and it doesn't rely on detecting before school classes.

**Review by psvenk — APPROVED** [review]
@jadebuckwalter I made a few changes; do you think this is ready to merge now?

**Pull request merged**
