### PR TITLE
login links

### PR DESCRIPTION
**Pull request by jshaw-7**
Fixed old links and their formatting on the Login page

### CODE REVIEW

**Review by tektaxi — CHANGES_REQUESTED** [review]
I like this! I think we could reduce the space between the district logo and the line with all the links, it feels like there's a lot of emptiness. Also not sure about the Instagram link...

**Review by PoobyMalom — APPROVED** [review]
Approved

**Comment by jshaw-7** [comment]
>

**Review by tektaxi — APPROVED** [review]
looks good! great work @jshaw-7 🎉

**Pull request merged**
