### PR TITLE
Add times to the schedule

### LINKED ISSUE #260: Display period times in schedule
It would be nice to be able to see what time each class is happening at. ex. Period 1 8:35-9:55 etc.

### PR DESCRIPTION
**Pull request by jadebuckwalter**
For each period, display the start and end time in the schedule.

### CODE REVIEW

**Comment by jadebuckwalter** [comment]
It would be great if someone who doesn't have an AM class could test this out.

**Review by tektaxi — APPROVED** [review]
Works well for me!

**Review by psvenk — CHANGES_REQUESTED** [review]
This does not work for me. I am working on a fix.

**Review by psvenk — CHANGES_REQUESTED** [review]
I just now refactored the code so that it is more efficient and clean and also works on my schedule, so it looks good to me apart from some stylistic comments: (a) we should display "AM"/"PM" instead of just leaving it implied (we can add a 24-hour time option once #23 is implemented), and (b) an en dash (`–`) should be used between times, not a hyphen (see [Butterick's Practical Typography](https://practicaltypography.com/hyphens-and-dashes.html)).

**Comment by psvenk** [comment]
By the way, the time formatting can be handled by [`Date.prototype.toLocaleTimeString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString). A fix is underway.

**Comment by jadebuckwalter** [comment]
@psvenk Great - that seems a lot easier. I can take care of these fixes if you'd like.

**Review by psvenk — APPROVED** [review]
Looks good to me!

**Comment by jadebuckwalter** [comment]
Looks good to me as well.

**Pull request merged**
